---
# :cached is a MacOS only flag to avoid a docker bug causing CPU spikes
version: "2"
services:
  app-frontend:
    container_name: "webTest_app_frontend_1"
    build:
      context: ./sickFitsApp/frontend/
      dockerfile: Dockerfile
    env_file:
      - sickFitsApp/frontend/env.dev
    network_mode: "host"
    ports:
      - "7777:7777"
    volumes:
      - ./sickFitsApp/frontend:/app:cached
    tty: true
    stdin_open: true

  app-backend:
    container_name: "webTest_app_backend_1"
    build:
      context: ./sickFitsApp/backend/
      dockerfile: Dockerfile
    env_file:
      - sickFitsApp/backend/env.dev
    network_mode: "host"
    ports:
      - "4444:4444"
    volumes:
      - ./sickFitsApp/backend:/app:cached
    tty: true
    stdin_open: true

  mysql:
    container_name: "webTest_mysql_1"
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    env_file:
      - mysql/env.dev
    network_mode: "host"
    ports:
      - "3306:3306"
    tty: true
    stdin_open: true

  todo-api:
    container_name: "webTest_todoApi_1"
    build:
      context: ./todoApp/api/
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "3306:3306"
      - "8000:8000"
    volumes:
      - ./todoApp/api:/app:cached
    command: "/app/bin/boot.sh"
    tty: true
    stdin_open: true
    depends_on:
      - mysql

volumes:
  cache:
    driver: local
  mysql-data:
    driver: local
