---
# :cached is a MacOS only flag to avoid a docker bug causing CPU spikes
version: "2"
services:
  mysql:
    container_name: "mysql_1"
    build:
      context: mysql/
      dockerfile: Dockerfile
    env_file:
      - mysql/env.dev
    ports:
      - "3306:3306"
    tty: true
    stdin_open: true

  todo-api:
    container_name: "todo-api_1"
    build:
      context: todoApp/api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./todoApp/api:/app:cached
    command: "/app/bin/boot.sh"
    tty: true
    stdin_open: true
    depends_on:
      - mysql

  todo-app:
    container_name: "todo-app_1"
    build:
      context: todoApp/frontend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./todoApp/frontend:/app:cached
    command: "/app/bin/boot.sh"
    tty: true
    stdin_open: true
    depends_on:
      - mysql
